<a href="https://colab.research.google.com/github/GruheshKurra/TensorFlow_Advanced/blob/main/TensorFlow_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [270]:
import tensorflow as tf
import numpy as np

In [271]:
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))

tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([1 3 3], shape=(3,), dtype=int32)


In [272]:
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))

tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([1 3 3], shape=(3,), dtype=int32)


In [273]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [274]:
tensor_bool = tf.constant([True,True,False])
print(tensor_bool)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [275]:
tensor_string = tf.constant(["hello world","hi "])
print(tensor_string)

tf.Tensor([b'hello world' b'hi '], shape=(2,), dtype=string)


In [276]:
tensor_one_d = tf.constant([2,0.,-3,8,90],dtype=tf.float32)
casted_tensor_one_d = tf.cast(tensor_one_d,dtype=tf.bool)
print(tensor_one_d)
print(casted_tensor_one_d)

tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float32)
tf.Tensor([ True False  True  True  True], shape=(5,), dtype=bool)


In [277]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [278]:
tensor_three_d = tf.constant([
    [[1,2,0],
    [3,5,-1]],

    [[10,2,0],
    [1,0,2]],

    [[5,8,0],
    [2,7,0]],

    [[2,1,9],
    [4,-3,32]],

])
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)


In [279]:
print(tensor_three_d.ndim)

3


In [280]:
print(tensor_three_d.shape)

(4, 2, 3)


In [281]:
t = tf.constant([[1, 1, 1], [2, 2, 2]],)
tf.size(t,out_type=tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [282]:
# shape of tensor 't' is [2, 2, 3]
t = tf.constant([[1, 1, 1], [2, 2, 2]])
tf.rank(t)  # 3

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [283]:
print(tf.shape(tensor_three_d))

tf.Tensor([4 2 3], shape=(3,), dtype=int32)


In [284]:
tensor_four_d = tf.constant([

[
    [[1,2,0],
    [3,5,-1]],

    [[10,2,0],
    [1,0,2]],

    [[5,8,0],
    [2,7,0]],

    [[2,1,9],
    [4,-3,32]],

],

[
    [[13,26,0],
    [3,5,-12]],

    [[10,2,0],
    [1,0,23]],

    [[5,8,0],
    [2,73,0]],

    [[2,1,9],
    [4,-30,32]],

],

[
    [[103,26,0],
    [3,50,-12]],

    [[100,2,0],
    [1,0,23]],

    [[5,28,0],
    [2,3,0]],

    [[22,1,9],
    [44,-320,32]],

],

])
print(tensor_four_d)

tf.Tensor(
[[[[   1    2    0]
   [   3    5   -1]]

  [[  10    2    0]
   [   1    0    2]]

  [[   5    8    0]
   [   2    7    0]]

  [[   2    1    9]
   [   4   -3   32]]]


 [[[  13   26    0]
   [   3    5  -12]]

  [[  10    2    0]
   [   1    0   23]]

  [[   5    8    0]
   [   2   73    0]]

  [[   2    1    9]
   [   4  -30   32]]]


 [[[ 103   26    0]
   [   3   50  -12]]

  [[ 100    2    0]
   [   1    0   23]]

  [[   5   28    0]
   [   2    3    0]]

  [[  22    1    9]
   [  44 -320   32]]]], shape=(3, 4, 2, 3), dtype=int32)


In [285]:
import numpy as np

In [286]:
np_array = np.array([1,2,4])
print(np_array)

[1 2 4]


In [287]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 4], shape=(3,), dtype=int64)


In [288]:
eye_tensor = tf.eye(
    num_rows=5,
    num_columns=None,
    batch_shape=[2,4],
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]


 [[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]], shape=(2, 4, 5, 5), dtype=float32)


In [289]:
fill_tensor = tf.fill(
    [1,3,4],5, name=None
)
print(fill_tensor)

tf.Tensor(
[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]], shape=(1, 3, 4), dtype=int32)


In [290]:
zeros_tensor = tf.zeros(
    [3,2],
    dtype=tf.dtypes.float32,
    name=None
)
print(zeros_tensor)

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [291]:
ones_tensor = tf.ones(
    [3,2],
    dtype=tf.dtypes.float32,
    name=None
)
print(ones_tensor)

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [292]:
ones_like_tensor = tf.ones_like(fill_tensor)
print(ones_like_tensor)

tf.Tensor(
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]], shape=(1, 3, 4), dtype=int32)


In [293]:
random_tensor = tf.random.normal(
    [3,2],
    mean=100.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[ 99.819695  99.04971 ]
 [ 99.96036   99.25746 ]
 [101.32315   99.381454]], shape=(3, 2), dtype=float32)


In [294]:
random_tensor = tf.random.uniform(
    [5,5],
    minval=0,
    maxval=1000,
    dtype=tf.dtypes.int32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[597 764 960 558  70]
 [817 340 143 777 334]
 [632 429 283 664 894]
 [120 292 511 585 171]
 [601 294 650 406 833]], shape=(5, 5), dtype=int32)


In [295]:
import tensorflow as tf
import numpy as np

In [296]:
tensor_zero_d = tf.constant(1)
print(tensor_zero_d)

tf.Tensor(1, shape=(), dtype=int32)


In [297]:
tensor_one_d = tf.constant([3,0,3], dtype = tf.float32)
print(tensor_one_d)

casted_tensor_one_d = tf.cast(tensor_one_d, dtype = tf.uint16)
print(casted_tensor_one_d)

tf.Tensor([3. 0. 3.], shape=(3,), dtype=float32)
tf.Tensor([3 0 3], shape=(3,), dtype=uint16)


In [298]:
tensor_two_d = tf.constant([[1,2,0],
                            [3,5,-1],
                            [1,5,6],
                            [2,3,8]])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [299]:
tensor_three_d = tf.constant([[[1,2,0],
                             [3,5,-1]],

                            [[10,2,0],
                             [1,0,2]],

                            [[5,8,0],
                             [2,7,0]],

                            [[2,1,9],
                             [4,-3,32]]])
print(tensor_three_d.ndim)

3


In [300]:
tensor_four_d = tf.constant([[[[1,2,0],
                             [3,5,-1]],

                            [[10,2,0],
                             [1,0,2]],

                            [[5,8,0],
                             [2,7,0]],

                            [[2,1,9],
                             [4,-3,32]]],



                             [[[0,2,5],
                             [5,3,1]],

                            [[0,2,0],
                             [-1,10,0]],

                            [[0,5,1],
                             [1,7,0]],

                            [[3,8,7],
                             [2,3,2]]],



                             [[[4,5,4],
                             [3,1,1]],

                            [[0,2,5],
                             [0,4,3]],

                            [[3,2,4],
                             [5,8,3]],

                            [[8,2,5],
                             [2,3,3]]]])
print(tensor_four_d)

tf.Tensor(
[[[[ 1  2  0]
   [ 3  5 -1]]

  [[10  2  0]
   [ 1  0  2]]

  [[ 5  8  0]
   [ 2  7  0]]

  [[ 2  1  9]
   [ 4 -3 32]]]


 [[[ 0  2  5]
   [ 5  3  1]]

  [[ 0  2  0]
   [-1 10  0]]

  [[ 0  5  1]
   [ 1  7  0]]

  [[ 3  8  7]
   [ 2  3  2]]]


 [[[ 4  5  4]
   [ 3  1  1]]

  [[ 0  2  5]
   [ 0  4  3]]

  [[ 3  2  4]
   [ 5  8  3]]

  [[ 8  2  5]
   [ 2  3  3]]]], shape=(3, 4, 2, 3), dtype=int32)


In [301]:
x = tf.constant(1, shape= (4,4))
print(x)

tf.Tensor(
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]], shape=(4, 4), dtype=int32)


In [302]:
x_np = np.array([3,4,5])
print(x_np)

[3 4 5]


In [303]:
x_tf = tf.convert_to_tensor(x_np, dtype = tf.float16)
print(x_tf)

tf.Tensor([3. 4. 5.], shape=(3,), dtype=float16)


In [304]:
identity_matrix = tf.eye(4, batch_shape=[2], dtype=tf.dtypes.float32, name=None)
print(identity_matrix)

tf.Tensor(
[[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]], shape=(2, 4, 4), dtype=float32)


In [305]:
filled_tensor = tf.fill([4,3], 1., )
print(filled_tensor)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(4, 3), dtype=float32)


In [306]:
ones_tensor = tf.ones([4,3], dtype = tf.float32)
print(ones_tensor)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(4, 3), dtype=float32)


In [307]:
zeros_tensor = tf.zeros([4,3], dtype = tf.float32)
print(zeros_tensor)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(4, 3), dtype=float32)


In [308]:
ones_like_tensor = tf.ones_like(tensor_four_d)
print(ones_like_tensor)
print(tensor_four_d.shape)

tf.Tensor(
[[[[1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]]]


 [[[1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]]]


 [[[1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]]]], shape=(3, 4, 2, 3), dtype=int32)
(3, 4, 2, 3)


In [309]:
normal_tensor = tf.random_normal_initializer(
    mean=0.0, stddev=0.05, seed=None
)

In [310]:
print(normal_tensor)

In [311]:
range_tensor = tf.range(start = 2, limit = 10, delta = 3)
print(range_tensor)

tf.Tensor([2 5 8], shape=(3,), dtype=int32)


In [312]:
print(tf.shape(tensor_three_d,))
print(tensor_three_d.shape)

tf.Tensor([4 2 3], shape=(3,), dtype=int32)
(4, 2, 3)


In [313]:
print(tf.size(tensor_four_d))

tf.Tensor(72, shape=(), dtype=int32)


In [314]:
g = tf.random.Generator.from_non_deterministic_state()
g.normal(shape=(2,), mean = 100, stddev = 1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([101.118454,  99.869705], dtype=float32)>

In [315]:
g = tf.random.Generator.from_non_deterministic_state()
g.uniform(shape=(2,), minval = 25, maxval = 40)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([27.235392, 32.366035], dtype=float32)>

In [316]:
tf.random.normal(
    (3,), mean=0.0, stddev=100.0, dtype=tf.dtypes.float32, seed=12, name="Random Number with Normal distribution"
)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([12.151812,  9.970952, 69.518616], dtype=float32)>

In [317]:
tf.random.uniform(
    (2,), minval=0, maxval=100, dtype=tf.dtypes.float32, seed=None, name=None
)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([20.179546, 34.707115], dtype=float32)>

In [318]:
tensor_indexed = tf.constant([3,6,2,4,6,66,7])
print(tensor_indexed[:])
print(tensor_indexed[0:4])
print(tensor_indexed[3:-3])

tf.Tensor([ 3  6  2  4  6 66  7], shape=(7,), dtype=int32)
tf.Tensor([3 6 2 4], shape=(4,), dtype=int32)
tf.Tensor([4], shape=(1,), dtype=int32)


In [319]:
tensor_two_d = tf.constant([[1,2,0],
                            [3,5,-1],
                            [1,5,6],
                            [2,3,8]])
print(tensor_two_d[...,1])

tf.Tensor([2 5 5 3], shape=(4,), dtype=int32)


In [320]:
tensor_three_d = tf.constant([


                              [[1,2,0],
                               [3,5,-1]],

                              [[10,2,0],
                               [1,0,2]],

                              [[5,8,0],
                               [2,7,0]],

                              [[2,1,9],
                               [4,-3,32]]


                              ])

print(tensor_three_d[ ... , : , 2])

tf.Tensor(
[[ 0 -1]
 [ 0  2]
 [ 0  0]
 [ 9 32]], shape=(4, 2), dtype=int32)


In [321]:
print(tf.expand_dims(tensor_three_d[ ... , : , 2],-1))

tf.Tensor(
[[[ 0]
  [-1]]

 [[ 0]
  [ 2]]

 [[ 0]
  [ 0]]

 [[ 9]
  [32]]], shape=(4, 2, 1), dtype=int32)


In [322]:
x_abs = tf.constant([-2.25, 3.25])
tf.abs(x_abs)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.25, 3.25], dtype=float32)>

In [323]:
tf.abs(tf.constant(-0.2))

<tf.Tensor: shape=(), dtype=float32, numpy=0.2>

In [324]:
x_abs_complex = tf.constant([-2.25 + 4.75j])
tf.abs(x_abs_complex)


<tf.Tensor: shape=(1,), dtype=float64, numpy=array([5.25594901])>

In [325]:
tf.sqrt((-2.25)**2 + 4.75**2)

<tf.Tensor: shape=(), dtype=float32, numpy=5.255949>

In [326]:
x_1 = tf.constant([[5,3,6,6,4,6]], dtype = tf.float32)
x_2 = tf.constant([[7], [5], [3]], dtype = tf.float32)

print(x_1.shape)
print(x_2.shape)
print(tf.math.multiply(x_1, x_2))

(1, 6)
(3, 1)
tf.Tensor(
[[35. 21. 42. 42. 28. 42.]
 [25. 15. 30. 30. 20. 30.]
 [15.  9. 18. 18. 12. 18.]], shape=(3, 6), dtype=float32)


In [327]:
x_argmax = tf.constant([[2, 20, 30, 3, 6],
                        [3, 11, 16, 1, 8],
                        [14, 45, 23, 5, 27]])

print(x_argmax.shape)
print(tf.math.argmin(x_argmax, axis = 1))

(3, 5)
tf.Tensor([0 3 3], shape=(3,), dtype=int64)


In [328]:
x_argmax = tf.constant([200, 120, 130, 3, 6])
print(tf.math.argmax(x_argmax))

tf.Tensor(0, shape=(), dtype=int64)


In [329]:
x_argmax = tf.constant([200, 120, 130, 300, 6])
print(tf.math.argmax(x_argmax))

tf.Tensor(3, shape=(), dtype=int64)


In [330]:
x = tf.constant([[2, 2], [3, 3]])
y = tf.constant([[3, 0], [1, 4]])
tf.pow(x, y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 8,  1],
       [ 3, 81]], dtype=int32)>

In [331]:
tf.pow(tf.constant(2) ,tf.constant(3))

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [332]:
tensor_two_d = tf.constant([[1,-2,0],
                            [3,5,100],
                            [1,5,6],
                            [2,3,8]], dtype = tf.float16)
print(tensor_two_d.shape)

print(tf.math.reduce_std(tensor_two_d, axis=0, keepdims=True, name=None))

(4, 3)
tf.Tensor([[ 0.829  2.861 41.38 ]], shape=(1, 3), dtype=float16)


In [333]:
tf.math.top_k(tensor_two_d, k = 2)

TopKV2(values=<tf.Tensor: shape=(4, 2), dtype=float16, numpy=
array([[  1.,   0.],
       [100.,   5.],
       [  6.,   5.],
       [  8.,   3.]], dtype=float16)>, indices=<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[0, 2],
       [2, 1],
       [2, 1],
       [2, 1]], dtype=int32)>)

In [334]:
x_1 = tf.constant([[1,2,0]])

x_2 = tf.constant([[1,2],
                  [3,5],
                  [4,5]])

x_3 = tf.constant([[1,2,0,2],
                  [3,5,-1,2]])

print(x_1.shape, x_2.shape, x_3.shape, tf.transpose(x_2).shape)
# x_3.T = 4,2
# x_2.T = 2,3
print(tf.transpose(x_3)@tf.transpose(x_2))
tf.linalg.matmul(
    x_3, x_2, transpose_a=True, transpose_b=False, adjoint_a=False, adjoint_b=True,
    a_is_sparse=False, b_is_sparse=False, output_type=None, name=None
)

(1, 3) (3, 2) (2, 4) (2, 3)
tf.Tensor(
[[ 7 18 19]
 [12 31 33]
 [-2 -5 -5]
 [ 6 16 18]], shape=(4, 3), dtype=int32)


<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 7, 18, 19],
       [12, 31, 33],
       [-2, -5, -5],
       [ 6, 16, 18]], dtype=int32)>

In [335]:
x_1@x_2

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[ 7, 12]], dtype=int32)>

In [336]:
tf.transpose(x_2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 4],
       [2, 5, 5]], dtype=int32)>

In [337]:
print(x_2)

tf.Tensor(
[[1 2]
 [3 5]
 [4 5]], shape=(3, 2), dtype=int32)


In [338]:
x_1 =  tf.constant([[[1,2],
                    [3,5]],

                    [[10,0],
                    [1,2]],

                    [[5,0],
                    [2,0]]])

x_2 = tf.constant([[[5,1,4],
                    [34,15,1]],

                    [[1,2,2],
                    [5,3,2]],

                    [[2,2,3],
                    [1,1,1]]])

print(tf.linalg.matmul(x_1, x_2))

tf.Tensor(
[[[ 73  31   6]
  [185  78  17]]

 [[ 10  20  20]
  [ 11   8   6]]

 [[ 10  10  15]
  [  4   4   6]]], shape=(3, 2, 3), dtype=int32)


In [339]:
x_1 =  tf.constant([[0,0],
                    [0,2]])

x_2 = tf.constant([[1,0,0],
                    [0,0,0]])

print(tf.linalg.matmul(x_1, x_2))

tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)


In [340]:
tensor_two_d = tf.constant([[1,-2,0],
                            [3,5,100],
                            [1,5,6],
                            [2,3,8]], dtype = tf.float16)

tensor_out_d = tf.constant([[1,0,0],
                            [0,5,0],
                            [0,0,6],
                            [0,0,0]], dtype = tf.float16)

#### ( m-n <= lower) and ( n-m <= upper)
# m -- rows, n --- columns
tf.linalg.band_part(tensor_two_d, 0, -1)

<tf.Tensor: shape=(4, 3), dtype=float16, numpy=
array([[  1.,  -2.,   0.],
       [  0.,   5., 100.],
       [  0.,   0.,   6.],
       [  0.,   0.,   0.]], dtype=float16)>

In [341]:
tensor_two_d_m_n = tf.constant([[0,-1,-2],
                                [1,0,-1],
                                [2,1,0],
                                [3,2,1]], dtype = tf.float16)

tensor_two_d_n_m = tf.constant([[0,1,2],
                                [-1,0,1],
                                [-2,-1,0],
                                [-3,-2,-1]], dtype = tf.float16)

m=1
n=2

In [342]:
tensor_two_d = tf.constant([[1,-2,0],
                            [3,5,100],
                            [1,5,6]], dtype = tf.float32)

tensor_two_d_inv = tf.linalg.inv(tensor_two_d)

In [343]:
tensor_two_d@tensor_two_d_inv

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.0000000e+00,  7.4505806e-09,  0.0000000e+00],
       [ 1.6391277e-07,  1.0000000e+00,  4.4703484e-08],
       [-5.2154064e-08,  7.4505806e-08,  1.0000000e+00]], dtype=float32)>

In [344]:
s,u,v = tf.linalg.svd(tensor_two_d)
print(s)
print(u)
print(v)

tf.Tensor([100.3663      5.1059036   1.2371687], shape=(3,), dtype=float32)
tf.Tensor(
[[-7.4980810e-04 -3.7569830e-01  9.2674178e-01]
 [ 9.9803799e-01 -5.8300879e-02 -2.2827482e-02]
 [ 6.2606096e-02  9.2490643e-01  3.7500489e-01]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 0.03044816  0.07330841  0.99684453]
 [ 0.0528536   0.9957936  -0.07484547]
 [ 0.998138   -0.05496572 -0.02644547]], shape=(3, 3), dtype=float32)


In [345]:
tensor_three_d = tf.constant([[[1,2,0],
                             [3,5,-1]],

                            [[10,2,0],
                             [1,0,2]],

                            [[5,8,0],
                             [2,7,0]],

                            [[2,1,9],
                             [4,-3,32]]])
print(tensor_three_d.shape)
x_exp = tf.expand_dims(tensor_three_d, axis = 3)
print(x_exp.shape)
print(tf.squeeze(x_exp, axis = 3))
print(tf.reshape(x_exp, [4,2,3]))

(4, 2, 3)
(4, 2, 3, 1)
tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)
tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)


In [346]:
x = tf.constant([[[2,3,4,5]]])
print(x.shape)
x_expanded = tf.expand_dims(x, axis = 0)
print(x_expanded)

(1, 1, 4)
tf.Tensor([[[[2 3 4 5]]]], shape=(1, 1, 1, 4), dtype=int32)


In [347]:
x_squeezed = tf.squeeze(x_expanded, axis = 0)
for i in range(2):
  x_squeezed = tf.squeeze(x_squeezed, axis = 0)

print(x_squeezed)

tf.Tensor([2 3 4 5], shape=(4,), dtype=int32)


In [348]:
x_reshape = tf.constant([[3,5,6,6],
                         [4,6,-1,2]])

print(tf.reshape(x_reshape, [-1]))
print(tf.reshape(x_reshape, [8]))

tf.Tensor([ 3  5  6  6  4  6 -1  2], shape=(8,), dtype=int32)
tf.Tensor([ 3  5  6  6  4  6 -1  2], shape=(8,), dtype=int32)


In [349]:
tf.transpose(x_reshape)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 5,  6],
       [ 6, -1],
       [ 6,  2]], dtype=int32)>

In [350]:
t1 = [[1, 2, 3],
      [4, 5, 6],
      [5, 6, 2],
      [1, 2, 1]]

t2 = [[7, 8, 9],
      [10, 11, 12],
      [0, 0, 2],
      [-1, 5, 2]]

print(tf.constant(t1).shape)
print(tf.constant(t2).shape)

tf.concat([t1, t2], axis = 0)

(4, 3)
(4, 3)


<tf.Tensor: shape=(8, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 5,  6,  2],
       [ 1,  2,  1],
       [ 7,  8,  9],
       [10, 11, 12],
       [ 0,  0,  2],
       [-1,  5,  2]], dtype=int32)>

In [351]:
tf.stack([t1,t2], axis = 2)

<tf.Tensor: shape=(4, 3, 2), dtype=int32, numpy=
array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]],

       [[ 5,  0],
        [ 6,  0],
        [ 2,  2]],

       [[ 1, -1],
        [ 2,  5],
        [ 1,  2]]], dtype=int32)>

In [352]:
tf.stack([t1,t2], axis = 0)

<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 5,  6,  2],
        [ 1,  2,  1]],

       [[ 7,  8,  9],
        [10, 11, 12],
        [ 0,  0,  2],
        [-1,  5,  2]]], dtype=int32)>

In [353]:
tf.concat([tf.expand_dims(t, axis = 0) for t in [t1,t2]], axis = 0)

<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 5,  6,  2],
        [ 1,  2,  1]],

       [[ 7,  8,  9],
        [10, 11, 12],
        [ 0,  0,  2],
        [-1,  5,  2]]], dtype=int32)>

In [354]:
t1 = [[1, 2, 3],
      [4, 5, 6],
      [5, 6, 2],
      [1, 2, 1]]

t2 = [[7, 8, 9],
      [10, 11, 12],
      [0, 0, 2],
      [-1, 5, 2]]

#4,3 - 4,3 --> 2,4,3
#4,3 - 4,3 --> 4,2,3
#4,3 - 4,3 --> 4,3,2

In [355]:
t = tf.constant([[1, 2, 3],
                 [4, 5, 6]])

paddings = tf.constant([[1, 5,],
                        [2, 3]])

tf.pad(t, paddings, "CONSTANT", constant_values = 0)

<tf.Tensor: shape=(8, 8), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 2, 3, 0, 0, 0],
       [0, 0, 4, 5, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>

In [356]:
params = tf.constant(['p0', 'p1', 'p2', 'p3', 'p4', 'p5'])
print(params.shape)
params[1:3+1]

(6,)


<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'p1', b'p2', b'p3'], dtype=object)>

In [357]:
tf.gather(params, [0,5,3], axis = 0)

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'p0', b'p5', b'p3'], dtype=object)>

In [358]:
params = tf.constant([

                      [[0, 1.0, 2.0],
                       [10.0, 11.0, 12.0],
                       [20.0, 21.0, 22.0],
                       [30.0, 31.0, 32.0]],

                      [[3, 1.0,21],
                       [1, 3, 88],
                       [0, 5, 55],
                       [0, 2, 30]]

                      ])
print(params.shape)
tf.gather(params, [2, 0], axis = 1)

(2, 4, 3)


<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[20., 21., 22.],
        [ 0.,  1.,  2.]],

       [[ 0.,  5., 55.],
        [ 3.,  1., 21.]]], dtype=float32)>

In [359]:
params = tf.constant([[3, 1.0,21],
                       [1, 3, 88],
                       [0, 5, 55],
                       [0, 2, 30]])

print(params.shape)
tf.gather(params, [2, 0], axis = 0)

(4, 3)


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.,  5., 55.],
       [ 3.,  1., 21.]], dtype=float32)>

In [360]:
indices = [2,1]

params = [['a', 'b'],
          ['c', 'd'],
          ['e', 'f']]

tf.gather_nd(params, indices)

<tf.Tensor: shape=(), dtype=string, numpy=b'f'>

In [361]:
indices = [[0, 1, 0], [1, 0, 1]]

params = [[['a0', 'b0'],
           ['c0', 'd0']],

          [['a1', 'b1'],
           ['c1', 'd1']]]

tf.gather_nd(params, indices)

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'c0', b'b1'], dtype=object)>

In [362]:
indices = [[[0, 1],
            [1, 0]],

            [[0, 0],
             [1, 1]]]

params = [[['a0', 'b0'],
           ['c0', 'd0']],

          [['a1', 'b1'],
           ['c1', 'd1']]]

tf.gather_nd(params, indices)

<tf.Tensor: shape=(2, 2, 2), dtype=string, numpy=
array([[[b'c0', b'd0'],
        [b'a1', b'b1']],

       [[b'a0', b'b0'],
        [b'c1', b'd1']]], dtype=object)>

In [363]:
indices = [[[0, 1],
            [1, 0]],

            [[0, 0],
             [1, 1]]]

params = [[['a0', 'b0'],
           ['c0', 'd0']],

          [['a1', 'b1'],
           ['c1', 'd1']]]


tf.gather_nd(params, indices, batch_dims = 1)

<tf.Tensor: shape=(2, 2), dtype=string, numpy=
array([[b'b0', b'c0'],
       [b'a1', b'd1']], dtype=object)>

In [364]:
indices = [[0,1],
           [1,0]]

params = [[['a0', 'b0'],
           ['c0', 'd0']],

          [['a1', 'b1'],
           ['c1', 'd1']]]


tf.gather_nd(params, indices, batch_dims = 1)

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'b0', b'c1'], dtype=object)>

In [365]:
tensor_two_d = tf.constant([[1,2,0],
                            [3,5,-1],
                            [1,5,6],
                            [2,3,8]])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [366]:
tensor_two_d =[[1,2,0],
               [3,],
               [1,5,6,5,6],
               [2,3]]
tensor_ragged = tf.ragged.constant(tensor_two_d)
print(tensor_ragged)

<tf.RaggedTensor [[1, 2, 0], [3], [1, 5, 6, 5, 6], [2, 3]]>


In [367]:
print(tf.RaggedTensor.from_row_lengths(
    values=[3, 1, 4, 1, 5, 9, 2, 6],
    row_lengths=[4, 0, 3, 1,0]))

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>


In [368]:
tensor_sparse = tf.sparse.SparseTensor(
    indices = [[1,1],[3,4]], values = [11,56], dense_shape = [5,6]
)

In [369]:
print(tensor_sparse)

SparseTensor(indices=tf.Tensor(
[[1 1]
 [3 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([11 56], shape=(2,), dtype=int32), dense_shape=tf.Tensor([5 6], shape=(2,), dtype=int64))


In [370]:
tf.sparse.to_dense(tensor_sparse)

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[ 0,  0,  0,  0,  0,  0],
       [ 0, 11,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 56,  0],
       [ 0,  0,  0,  0,  0,  0]], dtype=int32)>

In [371]:
tensor_string = tf.constant(["hello", "i am ", "a string"])
print(tensor_string)

tf.Tensor([b'hello' b'i am ' b'a string'], shape=(3,), dtype=string)


In [372]:
tf.strings.join(tensor_string, separator="+")

<tf.Tensor: shape=(), dtype=string, numpy=b'hello+i am +a string'>

In [373]:
x = tf.constant([1,2])

In [374]:
x_var = tf.Variable(x, name = 'var1')
print(x_var)

<tf.Variable 'var1:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>


In [375]:
x_var.assign_add([5,8])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([ 6, 10], dtype=int32)>

In [376]:
with tf.device('CPU:0'):
  x_1 = tf.constant([1,3,4])
  x_2 = tf.constant([1])

with tf.device('GPU:0'):
  x_3 = x_1 + x_2

print(x_1, x_1.device)
print(x_2, x_2.device)
print(x_3, x_3.device)

tf.Tensor([1 3 4], shape=(3,), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0
tf.Tensor([1], shape=(1,), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0
tf.Tensor([2 4 5], shape=(3,), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0


In [377]:
# !wget https://github.com/srihari-humbarwadi/datasets/releases/download/v0.1.0/data.zip

In [378]:
# !unzip /content/data.zip -d /content/dataset

In [379]:
import tensorflow as tf

In [380]:
input_var = tf.Variable(initial_value=10.)
with tf.GradientTape() as tape:
  result = tf.square(input_var)
gradient = tape.gradient(result, input_var)

In [381]:
print(gradient)

tf.Tensor(20.0, shape=(), dtype=float32)


In [382]:
input_const = tf.constant(10.)
with tf.GradientTape() as tape:
  tape.watch(input_const)
  result = tf.square(input_const)
gradient = tape.gradient(result, input_const)

In [383]:
print(gradient)

tf.Tensor(20.0, shape=(), dtype=float32)


In [384]:
time = tf.Variable(0.)
with tf.GradientTape() as outer_tape:
  with tf.GradientTape() as inner_tape:
    position = 4.9 * time ** 2
  speed = inner_tape.gradient(position, time)
acceleration = outer_tape.gradient(speed, time)

In [385]:
print(speed)

tf.Tensor(0.0, shape=(), dtype=float32)


In [386]:
print(acceleration)

tf.Tensor(9.8, shape=(), dtype=float32)


In [387]:
tensor_indexed = tf.constant([2,4,9,0,4,5,6,7])

In [388]:
tensor_indexed[3:7]

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 4, 5, 6], dtype=int32)>

In [389]:
print(tensor_indexed[0:7:1])
print(tensor_indexed[0:7:2])

tf.Tensor([2 4 9 0 4 5 6], shape=(7,), dtype=int32)
tf.Tensor([2 9 4 6], shape=(4,), dtype=int32)


In [390]:
tensor_indexed[-1]

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [391]:
print(tensor_indexed[0,...])
print(tensor_indexed[0:1,...])

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor([2], shape=(1,), dtype=int32)


In [392]:
tensor_indexed = tf.constant(
                              [[[1,2,0],
                                [3,5,-1]],

                              [[10,2,0],
                               [1,0,2]],

                              [[5,8,0],
                               [2,7,0]],

                              [[2,1,9],
                               [4,-3,32]]])

In [393]:
print(tensor_indexed.shape)

(4, 2, 3)


In [394]:
tensor_indexed[:,:,2]

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 0, -1],
       [ 0,  2],
       [ 0,  0],
       [ 9, 32]], dtype=int32)>

In [395]:
x = tf.constant([2,-1,3,-0.1,0])
print(tf.abs(x))

tf.Tensor([2.  1.  3.  0.1 0. ], shape=(5,), dtype=float32)


In [396]:
x = tf.constant(2+3j)
print(tf.abs(x))

tf.Tensor(3.605551275463989, shape=(), dtype=float64)


In [397]:
tf.sqrt(2.**2+3.**2)

<tf.Tensor: shape=(), dtype=float32, numpy=3.6055512>

In [398]:
x = tf.constant([2,3,5,7])
y = tf.constant([0,2,4,5])
print(tf.math.divide(x,y))

tf.Tensor([ inf 1.5  1.25 1.4 ], shape=(4,), dtype=float64)


In [399]:
x = tf.constant([[2,3,4,5]])
y = tf.constant([[1],[3]])
print(tf.math.maximum(x,y))

tf.Tensor(
[[2 3 4 5]
 [3 3 4 5]], shape=(2, 4), dtype=int32)


In [400]:
A = tf.constant([2, 20, 30, 3, 6])
tf.math.argmin(A)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [401]:
t_argmin = tf.constant([
  [3,1,9,6,5],
  [0,1,7,3,2],
  [1,5,1,2,0],
  [7,3,0,9,0],

])
tf.math.argmin(t_argmin,axis=1)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 0, 4, 2])>

In [402]:
x = tf.constant([[2, 2], [3, 3]])
y = tf.constant([[0, 1], [2, 3]])
tf.pow(x, y)  # [[256, 65536], [9, 27]]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  2],
       [ 9, 27]], dtype=int32)>

In [403]:
input_tensor = tf.constant([
  [3,1,9,6,5],
  [0,1,7,3,2],
  [1,5,1,2,0],
  [7,3,0,9,0],

])
print(tf.math.reduce_sum(
    input_tensor, axis=1, keepdims=True,
))


tf.Tensor(
[[24]
 [13]
 [ 9]
 [19]], shape=(4, 1), dtype=int32)


In [404]:
result = tf.math.top_k([1, 2, 98, 1, 1, 99, 3, 1, 3, 96, 4, 1],
                        k=1)
print(result)

TopKV2(values=<tf.Tensor: shape=(1,), dtype=int32, numpy=array([99], dtype=int32)>, indices=<tf.Tensor: shape=(1,), dtype=int32, numpy=array([5], dtype=int32)>)


In [405]:
x = tf.constant([-50,-5e10, 1.0, 50.0, 100.0])
tf.math.sigmoid(x)

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([1.9287499e-22, 0.0000000e+00, 7.3105860e-01, 1.0000000e+00,
       1.0000000e+00], dtype=float32)>

In [406]:
a = tf.constant([
  [1,5,1],
  [7,3,0],

])

b = tf.constant([
  [3,1],
  [0,1],
  [1,5],

])
print(a.shape, b.shape)
print(tf.linalg.matmul(a,b))
#print(a*b)

(2, 3) (3, 2)
tf.Tensor(
[[ 4 11]
 [21 10]], shape=(2, 2), dtype=int32)


In [407]:
a@b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 4, 11],
       [21, 10]], dtype=int32)>

In [408]:
a = tf.constant([
  [1,5,1],

])
print(a.shape,tf.transpose(a))

(1, 3) tf.Tensor(
[[1]
 [5]
 [1]], shape=(3, 1), dtype=int32)


In [409]:
a = tf.constant([
  [1,5,1],
])

b = tf.constant([
  [3,1],
  [0,1],
  [1,5],
])

print(a.shape, b.shape, tf.linalg.matrix_transpose(b).shape)

(1, 3) (3, 2) (2, 3)


In [410]:
a@b

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[ 4, 11]], dtype=int32)>

In [411]:
a = tf.constant(
            [[[1,2],
              [3,5]],

            [[10,2],
              [1,0]],

            [[5,8],
              [2,7]],

            [[2,1],
              [4,-3]]])


b = tf.constant(
            [[[1,2,0],
              [3,5,-1]],

            [[10,2,0],
              [1,0,2]],

            [[5,8,0],
              [2,7,0]],

            [[2,1,9],
              [4,-3,32]]])


In [412]:
print(a.shape,b.shape)

(4, 2, 2) (4, 2, 3)


In [413]:
print(tf.linalg.matmul(a,b))

tf.Tensor(
[[[  7  12  -2]
  [ 18  31  -5]]

 [[102  20   4]
  [ 10   2   0]]

 [[ 41  96   0]
  [ 24  65   0]]

 [[  8  -1  50]
  [ -4  13 -60]]], shape=(4, 2, 3), dtype=int32)


In [414]:
print(a[0],b[0])

tf.Tensor(
[[1 2]
 [3 5]], shape=(2, 2), dtype=int32) tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]], shape=(2, 3), dtype=int32)


In [415]:
a[2]@b[2]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[41, 96,  0],
       [24, 65,  0]], dtype=int32)>

In [416]:
a = tf.constant([
  [1,5,1],
  [7,9,3],
  [1,3,1],
])
m=n

In [417]:
print(a)
print(tf.linalg.band_part(a, 0, -1))# ==> Upper triangular part.
print(tf.linalg.band_part(a, -1, 0))# ==> Lower triangular part.
print(tf.linalg.band_part(a, 0, 0))# ==> Diagonal.

tf.Tensor(
[[1 5 1]
 [7 9 3]
 [1 3 1]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[1 5 1]
 [0 9 3]
 [0 0 1]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[1 0 0]
 [7 9 0]
 [1 3 1]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[1 0 0]
 [0 9 0]
 [0 0 1]], shape=(3, 3), dtype=int32)


In [418]:
a = tf.constant([
    [2,6,5,2],
    [2,-2,2,3],
    [1,5,4,0]
])
b = tf.constant([
    [2,9,0,3,0],
    [3,6,8,-2,2],
    [1,3,5,0,1],
    [3,0,2,0,5]
])
c = tf.linalg.matmul(a,b)
print(a.shape,b.shape)
print(c.shape)
print(c)

(3, 4) (4, 5)
(3, 5)
tf.Tensor(
[[33 69 77 -6 27]
 [ 9 12  0 10 13]
 [21 51 60 -7 14]], shape=(3, 5), dtype=int32)


In [419]:
tf.einsum("ij,jk->ik",a,b)

<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[33, 69, 77, -6, 27],
       [ 9, 12,  0, 10, 13],
       [21, 51, 60, -7, 14]], dtype=int32)>

In [420]:
a = tf.constant([2,6,5,2])
b = tf.constant([0,1,3,2])
tf.einsum("i,j->",a,b)

<tf.Tensor: shape=(), dtype=int32, numpy=90>

In [421]:
a = tf.constant([2,6,5,2])
b = tf.constant([0,1,3,2])
c = tf.einsum("i,j->ij",a,b)
print(c)
print(tf.reduce_sum(c))

print(tf.einsum("i,j->",a,b))

tf.Tensor(
[[ 0  2  6  4]
 [ 0  6 18 12]
 [ 0  5 15 10]
 [ 0  2  6  4]], shape=(4, 4), dtype=int32)
tf.Tensor(90, shape=(), dtype=int32)
tf.Tensor(90, shape=(), dtype=int32)


In [422]:
b = tf.constant([
    [2,9,0,3,0],
    [3,6,8,-2,2],
    [1,3,5,0,1],
    [3,0,2,0,5]
])
tf.einsum("ij->ji",b)

<tf.Tensor: shape=(5, 4), dtype=int32, numpy=
array([[ 2,  3,  1,  3],
       [ 9,  6,  3,  0],
       [ 0,  8,  5,  2],
       [ 3, -2,  0,  0],
       [ 0,  2,  1,  5]], dtype=int32)>

In [423]:
a = tf.constant([
    [2,6,5,2],
    [2,-2,2,3],
    [1,5,4,0]
])
b = tf.constant([
    [2,9,0,3],
    [3,6,8,-2],
    [1,3,5,0],
])
tf.einsum("ij,ij->ij",a,b)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[  4,  54,   0,   6],
       [  6, -12,  16,  -6],
       [  1,  15,  20,   0]], dtype=int32)>

In [424]:
a*b

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[  4,  54,   0,   6],
       [  6, -12,  16,  -6],
       [  1,  15,  20,   0]], dtype=int32)>

In [425]:
a = tf.constant([

    [[2,6,5,2],
     [2,-2,2,3],
     [1,5,4,0]],

    [[2,6,5,2],
     [2,-2,2,3],
     [1,5,4,0]]
    ])
b = tf.constant([
    [[2,9,0,3,0],
     [3,6,8,-2,2],
     [1,3,5,0,1],
     [3,0,2,0,5]],

    [[2,9,0,3,0],
     [3,6,8,-2,2],
     [1,3,5,0,1],
     [3,0,2,0,5]]
])

In [426]:
print(a.shape,b.shape)

(2, 3, 4) (2, 4, 5)


In [427]:
tf.einsum("bij,bjk->bik",a,b)

<tf.Tensor: shape=(2, 3, 5), dtype=int32, numpy=
array([[[33, 69, 77, -6, 27],
        [ 9, 12,  0, 10, 13],
        [21, 51, 60, -7, 14]],

       [[33, 69, 77, -6, 27],
        [ 9, 12,  0, 10, 13],
        [21, 51, 60, -7, 14]]], dtype=int32)>

In [428]:
a = tf.constant([

    [[2,6,5,2],
     [2,-2,2,3],
     [1,5,4,0]],

    [[2,6,5,2],
     [2,-2,2,3],
     [1,5,4,0]]
    ])

print(tf.linalg.matmul(a,a,transpose_b=True))
print(a.shape)

tf.Tensor(
[[[69  8 52]
  [ 8 21  0]
  [52  0 42]]

 [[69  8 52]
  [ 8 21  0]
  [52  0 42]]], shape=(2, 3, 3), dtype=int32)
(2, 3, 4)


In [429]:
a = tf.constant([1,3,4,5,6,7])
print(a.shape)

(6,)


In [430]:
tf.expand_dims(a,axis=0)

<tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[1, 3, 4, 5, 6, 7]], dtype=int32)>

In [431]:
tf.expand_dims(a,axis=1)

<tf.Tensor: shape=(6, 1), dtype=int32, numpy=
array([[1],
       [3],
       [4],
       [5],
       [6],
       [7]], dtype=int32)>

In [432]:
a = tf.constant([

    [[2,6,5,2],
     [2,-2,2,3],
     [1,5,4,0]],

    [[2,6,5,2],
     [2,-2,2,3],
     [1,5,4,0]]
    ])
print(a.shape)
1,2,3,4

(2, 3, 4)


(1, 2, 3, 4)

In [433]:
c = tf.expand_dims(a,axis=-1)
print(c.shape)
print(tf.squeeze(c,axis=-1))

(2, 3, 4, 1)
tf.Tensor(
[[[ 2  6  5  2]
  [ 2 -2  2  3]
  [ 1  5  4  0]]

 [[ 2  6  5  2]
  [ 2 -2  2  3]
  [ 1  5  4  0]]], shape=(2, 3, 4), dtype=int32)


In [434]:
a = tf.constant([1,2,3,4,5,6,7,8,9])
print(tf.reshape(a,[3,-1,1]))

tf.Tensor(
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]], shape=(3, 3, 1), dtype=int32)


In [435]:
t1 = tf.constant(
    [[1, 4, 3],
      [2, 5, 6]])
print(t1.shape)

(2, 3)


In [436]:
tf.reshape(t1,[6])

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 4, 3, 2, 5, 6], dtype=int32)>

In [437]:
t1 = tf.constant(
    [[1, 2, 3],
     [4, 5, 6]])

t2 = tf.constant(
    [[7, 8, 9],
     [10, 11, 12]])
print(t1.shape, t2.shape)

(2, 3) (2, 3)


In [438]:
tf.concat([tf.expand_dims(t1,-1),
          tf.expand_dims(t2,-1)],axis=-1)

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]]], dtype=int32)>

In [439]:
tf.stack([t1,t2],axis=-1)

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]]], dtype=int32)>

In [440]:
tf.concat([t1,t2],axis=0)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [441]:
t1 = tf.constant([
    [[1, 2],
     [2, 3]],

    [[4, 4],
     [5, 3]]
])
t2 = tf.constant([
    [[7, 4],
     [8, 4]],

    [[2, 10],
     [15, 11]]
])
print(t1.shape,t2.shape)


(2, 2, 2) (2, 2, 2)


In [442]:
print(tf.concat([t1, t2], 0))

tf.Tensor(
[[[ 1  2]
  [ 2  3]]

 [[ 4  4]
  [ 5  3]]

 [[ 7  4]
  [ 8  4]]

 [[ 2 10]
  [15 11]]], shape=(4, 2, 2), dtype=int32)


In [443]:
t = tf.constant([[1, 2, 3],
                 [4, 5, 6]])
paddings = tf.constant([[4, 1,],
                        [2, 4]])
# 'constant_values' is 0.
# rank of 't' is 2.
print(tf.pad(t, paddings, "CONSTANT", constant_values=9))

tf.Tensor(
[[9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9]
 [9 9 1 2 3 9 9 9 9]
 [9 9 4 5 6 9 9 9 9]
 [9 9 9 9 9 9 9 9 9]], shape=(7, 9), dtype=int32)


In [444]:
a = tf.constant([4,5,6,7])
print(a[1:3])

tf.Tensor([5 6], shape=(2,), dtype=int32)


In [445]:
tf.gather(a,[0,3,1],axis=0)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 7, 5], dtype=int32)>

In [446]:
b = tf.constant([
    [2,9,0,3,0],
    [3,6,8,-2,2],
    [1,3,5,0,1],
    [3,0,2,0,5]
])

In [447]:
tf.gather_nd(b,[[1],
                [3]])

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[ 3,  6,  8, -2,  2],
       [ 3,  0,  2,  0,  5]], dtype=int32)>

In [448]:
tf.gather(b,[1,3],axis=0)

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[ 3,  6,  8, -2,  2],
       [ 3,  0,  2,  0,  5]], dtype=int32)>

In [449]:
tf.gather(b,[[1,3],
             [2,0]],axis=0)

<tf.Tensor: shape=(2, 2, 5), dtype=int32, numpy=
array([[[ 3,  6,  8, -2,  2],
        [ 3,  0,  2,  0,  5]],

       [[ 1,  3,  5,  0,  1],
        [ 2,  9,  0,  3,  0]]], dtype=int32)>

In [450]:
a = tf.ragged.constant([
    [1,3],
    [4,5,6],
    [7]
])
print(a)

<tf.RaggedTensor [[1, 3], [4, 5, 6], [7]]>


In [451]:
tf.ragged.boolean_mask(  # Mask a 2D RaggedTensor.
    tf.ragged.constant([[1, 2, 3], [4], [5, 6]]),
    tf.ragged.constant([[False, False, True], [False], [True, True]])).to_list()

[[3], [], [5, 6]]

In [452]:
values = [3, 1, 4, 1, 5, 9, 2, 6,7]


print(tf.RaggedTensor.from_uniform_row_length(values, uniform_row_length=3))


<tf.RaggedTensor [[3, 1, 4],
 [1, 5, 9],
 [2, 6, 7]]>


In [453]:
sparse_tensor = tf.sparse.SparseTensor(
    indices=[[0, 0],
             [2, 5]], values=[5, 9], dense_shape=[5,6])

In [454]:
sparse_tensor

SparseTensor(indices=tf.Tensor(
[[0 0]
 [2 5]], shape=(2, 2), dtype=int64), values=tf.Tensor([5 9], shape=(2,), dtype=int32), dense_shape=tf.Tensor([5 6], shape=(2,), dtype=int64))

In [455]:
tf.sparse.to_dense(sparse_tensor)

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 9],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int32)>

In [456]:
tensor_string_1 = tf.constant(["i am ", "a", "string"])
tensor_string_2 = tf.constant(["i am ", "not a", "string"])

In [457]:
tf.strings.join([tensor_string_1,tensor_string_2], separator="+")

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'i am +i am ', b'a+not a', b'string+string'], dtype=object)>

In [458]:
x = tf.constant([1,2,3,4,5])

In [459]:
x_var = tf.Variable(x)

In [460]:
print(x,x_var)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32) <tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>


In [461]:
x_var.assign_sub([5,5,5,5,5])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int32, numpy=array([-4, -3, -2, -1,  0], dtype=int32)>

In [462]:
x_var.assign([5,5,5,5,5])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int32, numpy=array([5, 5, 5, 5, 5], dtype=int32)>